//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileBrowser.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileBrowser.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Directory.
        /// </summary>
        internal static string AddDirectory {
            get {
                return ResourceManager.GetString("AddDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Extension.
        /// </summary>
        internal static string AddExtension {
            get {
                return ResourceManager.GetString("AddExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path of the directory cannot be empty..
        /// </summary>
        internal static string ArgumentExceptionPathFolder {
            get {
                return ResourceManager.GetString("ArgumentExceptionPathFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        internal static string CollapseAll {
            get {
                return ResourceManager.GetString("CollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        internal static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directories.
        /// </summary>
        internal static string Directories {
            get {
                return ResourceManager.GetString("Directories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This extension already exists in the list.
        /// </summary>
        internal static string DuplicateExtensionDescription {
            get {
                return ResourceManager.GetString("DuplicateExtensionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate extension.
        /// </summary>
        internal static string DuplicateExtensionTitle {
            get {
                return ResourceManager.GetString("DuplicateExtensionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder already exists in the list.
        /// </summary>
        internal static string DuplicateFolderDescription {
            get {
                return ResourceManager.GetString("DuplicateFolderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Folder.
        /// </summary>
        internal static string DuplicateFolderTitle {
            get {
                return ResourceManager.GetString("DuplicateFolderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This directory does not exist anymore on your computer.
        /// </summary>
        internal static string ErrorDirectoryNotFound {
            get {
                return ResourceManager.GetString("ErrorDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not selected any directory yet. Go to the settings menu..
        /// </summary>
        internal static string ErrorNoDirectories {
            get {
                return ResourceManager.GetString("ErrorNoDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matches found.
        /// </summary>
        internal static string ErrorNoMatches {
            get {
                return ResourceManager.GetString("ErrorNoMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand directories on load and refresh.
        /// </summary>
        internal static string ExpandInfo {
            get {
                return ResourceManager.GetString("ExpandInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensions.
        /// </summary>
        internal static string Extensions {
            get {
                return ResourceManager.GetString("Extensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On program startup, the list will automatically refresh.
        /// </summary>
        internal static string HelpFour {
            get {
                return ResourceManager.GetString("HelpFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to settings and add the directories you want this program to scan.
        /// </summary>
        internal static string HelpOne {
            get {
                return ResourceManager.GetString("HelpOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When done, exit the settings menu and click on &quot;Refresh&quot;. This will generate a list of all the files that match the extensions in the specified folders.
        /// </summary>
        internal static string HelpThree {
            get {
                return ResourceManager.GetString("HelpThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add the extensions of the files you want to scan.
        /// </summary>
        internal static string HelpTwo {
            get {
                return ResourceManager.GetString("HelpTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The extension cannot be empty.
        /// </summary>
        internal static string InvalidExtensionEmpty {
            get {
                return ResourceManager.GetString("InvalidExtensionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid extension.
        /// </summary>
        internal static string InvalidExtensionTitle {
            get {
                return ResourceManager.GetString("InvalidExtensionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid language was selected.
        /// </summary>
        internal static string InvalidLanguageDescription {
            get {
                return ResourceManager.GetString("InvalidLanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Language.
        /// </summary>
        internal static string InvalidLangugeTitle {
            get {
                return ResourceManager.GetString("InvalidLangugeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Background.
        /// </summary>
        internal static string ListBackground {
            get {
                return ResourceManager.GetString("ListBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Text.
        /// </summary>
        internal static string ListForeground {
            get {
                return ResourceManager.GetString("ListForeground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Background.
        /// </summary>
        internal static string MenuBackground {
            get {
                return ResourceManager.GetString("MenuBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Text.
        /// </summary>
        internal static string MenuForeground {
            get {
                return ResourceManager.GetString("MenuForeground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string MenuRefresh {
            get {
                return ResourceManager.GetString("MenuRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires restart.
        /// </summary>
        internal static string RequiresRestart {
            get {
                return ResourceManager.GetString("RequiresRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
    }
}
